# This workflow will install Python dependencies and run the VIX futures downloader script

name: VIX Futures Downloader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "15 23 * * 1-5"  # Runs at 23:15 UTC Mon-Fri (2 hours after CBOE VIX futures close at 4:15 PM ET / 21:15 UTC)

permissions:
  contents: write  # Need write permission to update the master CSV file

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for commits

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas requests beautifulsoup4

    - name: Run VIX Futures Downloader
      run: python vix_futures_downloader.py

    - name: Commit and Push new data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add data/vix_futures_master.csv
        git add data/vix_futures_*.csv
        git add data/vix_downloader.log
        git add data/cboe_debug.html
        git commit -m "Daily VIX futures update $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push

    - name: Upload CSV files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vix-futures-data
        path: |
          data/*.csv
          data/*.log
        retention-days: 399  # Keeps the artifact for 399 days

    - name: Display log file (for debugging)
      if: always()  # Run even if previous steps fail
      run: |
        echo "=== VIX FUTURES DOWNLOADER LOG ==="
        cat data/vix_downloader.log
        echo "==================================="
