# This workflow will install Python dependencies and run the ETF scraper script
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python ETF Scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "15 5 * * *"  # Runs daily at 5:15 AM UTC

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run ETF Scraper
      run: python download_etf_csv.py

    - name: Upload CSV file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: etf-data
        path: data/*.csv
