# This workflow will install Python dependencies, run the ETF scraper, and commit results to the repo.

name: Python ETF Scraper

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC

permissions:
  contents: write  # Grant push permissions to the workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # We will use PAT for pushing

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run ETF Scraper
      run: python download_etf_csv.py

    - name: Commit and Push Results
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add pcfs/*.csv
        git commit -m "Updated ETF Data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
